name: file_utils
description: Cross platform file utils
version: 0.0.2+1
publish_to: "none"

environment:
  sdk: ">=2.18.0-189.0.dev <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  file_picker: ^4.6.1
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  share_plus: ^4.0.10
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
